package com.example.maciej.complexdatabases.object.box.model;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.apihint.Internal;

/**
 * Created by Maciej on 2017-05-12.
 */

@Entity
public class Song {

    @Id
    private long id;
    private String oldId;
    private String title;

    @Generated(1114752825)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Song(long id, String oldId, String title) {
        this.id = id;
        this.oldId = oldId;
        this.title = title;
    }

    @Generated(87031450)
    public Song() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getOldId() {
        return oldId;
    }

    public void setOldId(String oldId) {
        this.oldId = oldId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
}
